id: test
require:
  - weld_deps

data_pack:
  load: src

pipeline:
  - mecha

output: dist

meta:
  weld_deps:
    clean_load_tag: False
    deps:
      - id: "simpledrawer"
        match: "1.10.2"
        source: "smithed"